// LIBRARIES
import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

// COMPONENTS
// import LoginForm from "components/organisms/loginForm";

const Account: NextPage = () => {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Login - Account </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Login / Account
        </h1>
        <div className="flex items-center justify-center gap-4">
          <button className="btn btn-primary" onClick={() => signIn("google")}>
            Login With Google
          </button>
          <button className="btn btn-primary" onClick={() => signOut()}>
            Logout
          </button>
          <button
            className="btn btn-primary"
            onClick={() => console.log("session", { session })}
          >
            console log session: {typeof session}
          </button>
          <button
            className="btn btn-primary"
            onClick={() => console.log("user", { status })}
          >
            console log status: {status}
          </button>
        </div>
      </main>
    </>
  );
};

export default Account;
